# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: MindMapVault.MindMapVaultFOSS
PackageVersion: 0.6.3
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.mindmapvault.com/foss/windows/0.6.3/MindMapVault-FOSS_0.6.3_x64-setup.exe
  InstallerSha256: BF77A83DBACB65F07B8197EF3228F40E4C5BAA1776836CFBBEEEA0CEE4F47877
ManifestType: installer
ManifestVersion: 1.12.0
